/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionClearButton: typeof import('./components/ActionClearButton.vue')['default']
    ActionDeleteButton: typeof import('./components/ActionDeleteButton.vue')['default']
    ActionEditButton: typeof import('./components/ActionEditButton.vue')['default']
    ActionFormButtonState: typeof import('./components/ActionFormButtonState.vue')['default']
    ActionFormReturnButton: typeof import('./components/ActionFormReturnButton.vue')['default']
    ActionGenericButton: typeof import('./components/ActionGenericButton.vue')['default']
    ActionNewButton: typeof import('./components/ActionNewButton.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Breadcrumbs: typeof import('./components/Breadcrumbs.vue')['default']
    BreadcrumbsWithBackButton: typeof import('./components/BreadcrumbsWithBackButton.vue')['default']
    BreadcrumbsWithTitle: typeof import('./components/BreadcrumbsWithTitle.vue')['default']
    CustomFilters: typeof import('./components/CustomFilters.vue')['default']
    FiltersDialog: typeof import('./components/FiltersDialog.vue')['default']
    GenericCardsWithActions: typeof import('./components/GenericCardsWithActions.vue')['default']
    GenericFormWithActions: typeof import('./components/GenericFormWithActions.vue')['default']
    GenericTable: typeof import('./components/GenericTable.vue')['default']
    GenericTableWithActions: typeof import('./components/GenericTableWithActions.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
